[project]
name = "slurmd"
version = "0.0"
requires-python = "==3.14.*"
dependencies = [
    "ops",
    "slurmutils",
    "ubuntu-drivers-common",
    "charmed-hpc-libs[ops]",
    "charmed-slurm-slurmd-interface",
    "cosl",
    "pydantic",
    "python-apt",
    "slurm-ops",
]

[tool.repository]
libraries = [
    "prometheus_k8s.prometheus_scrape"
]
