[project]
name = "slurmdbd"
version = "0.0"
requires-python = "==3.14.*"
dependencies = [
    "ops",
    "slurmutils",
    "charmed-hpc-libs[ops]",
    "charmed-slurm-slurmdbd-interface",
    "cosl",
    "pydantic",
    "slurm-ops"
]

[tool.repository]
libraries = ["data-platform-libs.data_interfaces", "grafana-agent.cos_agent"]
